#include "Banks/SetAutoBank.h"
#include "StateGame.h"

BANKREF(level1Map)
// emerald count 30
const unsigned char level1Map[] = {
	O_D, GRS, GRS, GRS, BAG, GRS, GRS, GRS, GRS, GRS, CBR, HHH, HHH, HHH, O_L,
	VVV, GRS, GRS, EMR, EMR, GRS, GRS, EMR, GRS, GRS, VVV, GRS, BAG, GRS, GRS,
	VVV, BAG, GRS, EMR, EMR, GRS, GRS, EMR, GRS, GRS, VVV, GRS, GRS, GRS, GRS,
	VVV, GRS, GRS, EMR, EMR, BAG, GRS, EMR, BAG, GRS, VVV, GRS, EMR, EMR, EMR,
	VVV, GRS, GRS, EMR, EMR, GRS, GRS, EMR, GRS, GRS, VVV, GRS, EMR, EMR, EMR,
	CTR, CBL, GRS, EMR, EMR, GRS, GRS, EMR, GRS, GRS, VVV, GRS, EMR, EMR, EMR,
	GRS, VVV, GRS, GRS, GRS, GRS, BAG, GRS, BAG, GRS, VVV, GRS, GRS, GRS, GRS,
	GRS, CTR, HHH, HHH, CBL, GRS, GRS, GRS, GRS, GRS, VVV, GRS, GRS, GRS, GRS,
	EMR, GRS, GRS, GRS, VVV, GRS, GRS, GRS, GRS, GRS, VVV, GRS, GRS, GRS, EMR,
	EMR, EMR, GRS, GRS, CTR, HHH, HHH, HHH, HHH, HHH, CTL, GRS, GRS, EMR, EMR,
};

BANKREF(level2Map)
// emerald count 41
const unsigned char level2Map[] = {
	O_R, HHH, HHH, HHH, HHH, CBL, GRS, GRS, BAG, GRS, BAG, GRS, GRS, CBR, O_L,
	GRS, EMR, EMR, GRS, GRS, VVV, GRS, GRS, GRS, GRS, GRS, GRS, GRS, VVV, GRS,
	GRS, EMR, EMR, GRS, GRS, VVV, GRS, EMR, EMR, EMR, EMR, EMR, GRS, VVV, GRS,
	BAG, EMR, EMR, BAG, GRS, VVV, GRS, EMR, EMR, EMR, EMR, EMR, GRS, VVV, GRS,
	EMR, EMR, EMR, EMR, GRS, VVV, GRS, GRS, GRS, GRS, GRS, GRS, GRS, VVV, GRS,
	EMR, EMR, EMR, EMR, GRS, VVV, GRS, BAG, GRS, GRS, CBR, HHH, HHH, CTL, GRS,
	GRS, EMR, EMR, GRS, GRS, VVV, GRS, EMR, EMR, GRS, VVV, GRS, GRS, GRS, GRS,
	GRS, BAG, BAG, GRS, GRS, VVV, EMR, EMR, EMR, EMR, VVV, GRS, EMR, EMR, GRS,
	EMR, GRS, GRS, GRS, GRS, VVV, GRS, EMR, EMR, GRS, VVV, GRS, EMR, EMR, GRS,
	EMR, EMR, GRS, GRS, GRS, CTR, HHH, HHH, HHH, HHH, CTL, GRS, GRS, GRS, GRS,
};

BANKREF(level3Map)
// emerald count 51
const unsigned char level3Map[] = {
	O_R, HHH, HHH, HHH, CBL, BAG, GRS, BAG, GRS, BAG, CBR, HHH, HHH, HHH, O_L,
	EMR, EMR, GRS, GRS, VVV, GRS, EMR, GRS, EMR, GRS, VVV, GRS, BAG, BAG, GRS,
	EMR, GRS, GRS, GRS, VVV, GRS, EMR, GRS, EMR, GRS, VVV, GRS, EMR, EMR, GRS,
	GRS, BAG, BAG, GRS, VVV, GRS, EMR, GRS, EMR, GRS, VVV, EMR, EMR, EMR, EMR,
	EMR, EMR, EMR, EMR, VVV, GRS, EMR, GRS, EMR, GRS, VVV, EMR, EMR, EMR, EMR,
	EMR, EMR, EMR, EMR, CTR, HHH, HHH, T_D, HHH, HHH, CTL, GRS, EMR, EMR, GRS,
	GRS, EMR, EMR, GRS, GRS, EMR, GRS, VVV, GRS, EMR, GRS, GRS, EMR, EMR, GRS,
	GRS, EMR, EMR, GRS, GRS, EMR, GRS, VVV, GRS, EMR, GRS, GRS, GRS, GRS, GRS,
	EMR, GRS, GRS, GRS, GRS, EMR, GRS, VVV, GRS, EMR, GRS, GRS, GRS, GRS, EMR,
	EMR, EMR, GRS, GRS, GRS, EMR, GRS, T_U, GRS, EMR, GRS, GRS, GRS, EMR, EMR,
};

BANKREF(level4Map)
// emerald count 65
const unsigned char level4Map[] = {
	O_R, CBL, BAG, EMR, EMR, EMR, EMR, BAG, EMR, EMR, EMR, EMR, BAG, CBR, O_L,
	EMR, VVV, GRS, GRS, EMR, EMR, EMR, EMR, EMR, EMR, EMR, GRS, GRS, VVV, EMR,
	EMR, CTR, HHH, CBL, GRS, EMR, EMR, EMR, EMR, EMR, GRS, CBR, HHH, CTL, EMR,
	EMR, GRS, GRS, VVV, GRS, GRS, EMR, EMR, EMR, GRS, GRS, VVV, GRS, GRS, EMR,
	GRS, GRS, GRS, CTR, HHH, CBL, GRS, EMR, GRS, CBR, HHH, CTL, GRS, GRS, GRS,
	GRS, GRS, BAG, GRS, GRS, VVV, GRS, BAG, GRS, VVV, GRS, GRS, BAG, GRS, GRS,
	GRS, GRS, EMR, GRS, GRS, VVV, EMR, EMR, EMR, VVV, GRS, GRS, EMR, GRS, GRS,
	GRS, EMR, EMR, EMR, GRS, CTR, HHH, T_D, HHH, CTL, GRS, EMR, EMR, EMR, GRS,
	EMR, EMR, EMR, EMR, EMR, GRS, EMR, VVV, EMR, GRS, EMR, EMR, EMR, EMR, EMR,
	EMR, EMR, EMR, EMR, EMR, GRS, EMR, O_U, EMR, GRS, EMR, EMR, EMR, EMR, EMR,
};

BANKREF(level5Map)
// emerald count 77
const unsigned char level5Map[] = {
	CBR, HHH, HHH, HHH, HHH, HHH, HHH, T_D, HHH, HHH, HHH, HHH, HHH, HHH, CBL,
	VVV, BAG, EMR, EMR, EMR, EMR, BAG, VVV, EMR, EMR, EMR, EMR, EMR, EMR, VVV,
	VVV, EMR, EMR, EMR, EMR, EMR, EMR, VVV, GRS, EMR, EMR, BAG, EMR, GRS, VVV,
	VVV, GRS, EMR, EMR, EMR, EMR, GRS, VVV, EMR, EMR, BAG, EMR, EMR, EMR, VVV,
	VVV, EMR, EMR, EMR, EMR, EMR, EMR, VVV, GRS, EMR, EMR, EMR, EMR, GRS, VVV,
	VVV, GRS, EMR, EMR, EMR, EMR, GRS, VVV, BAG, EMR, EMR, EMR, EMR, EMR, VVV,
	VVV, EMR, EMR, BAG, EMR, EMR, EMR, VVV, GRS, EMR, EMR, EMR, EMR, GRS, VVV,
	VVV, GRS, EMR, EMR, BAG, EMR, GRS, VVV, EMR, EMR, EMR, EMR, EMR, EMR, VVV,
	VVV, EMR, EMR, EMR, EMR, EMR, EMR, VVV, EMR, EMR, EMR, EMR, EMR, EMR, VVV,
	CTR, HHH, HHH, HHH, HHH, HHH, HHH, T_U, HHH, HHH, HHH, HHH, HHH, HHH, CTL,
};

BANKREF(level6Map)
// emerald count 52
const unsigned char level6Map[] = {
	CBR, HHH, HHH, HHH, HHH, T_D, HHH, T_D, HHH, T_D, HHH, HHH, HHH, HHH, CBL,
	VVV, EMR, BAG, EMR, EMR, VVV, GRS, VVV, GRS, VVV, EMR, EMR, BAG, EMR, VVV,
	VVV, EMR, EMR, EMR, GRS, VVV, BAG, VVV, BAG, VVV, GRS, EMR, EMR, EMR, VVV,
	VVV, EMR, EMR, EMR, CBR, CTL, GRS, VVV, GRS, CTR, CBL, EMR, EMR, EMR, VVV,
	VVV, EMR, EMR, GRS, VVV, GRS, EMR, VVV, EMR, GRS, VVV, GRS, EMR, EMR, VVV,
	VVV, EMR, EMR, CBR, CTL, GRS, EMR, VVV, EMR, GRS, CTR, CBL, EMR, EMR, VVV,
	VVV, EMR, GRS, VVV, GRS, EMR, EMR, VVV, EMR, EMR, GRS, VVV, GRS, EMR, VVV,
	VVV, EMR, CBR, CTL, BAG, EMR, EMR, VVV, EMR, EMR, BAG, CTR, CBL, EMR, VVV,
	VVV, EMR, VVV, EMR, EMR, EMR, EMR, VVV, EMR, EMR, EMR, EMR, VVV, EMR, VVV,
	CTR, HHH, T_U, HHH, HHH, HHH, HHH, T_U, HHH, HHH, HHH, HHH, T_U, HHH, CTL,
};

BANKREF(level7Map)
// emerald count 92
const unsigned char level7Map[] = {
	O_R, CBL, EMR, EMR, EMR, EMR, EMR, O_D, EMR, EMR, EMR, EMR, EMR, CBR, O_L,
	GRS, VVV, EMR, BAG, EMR, BAG, EMR, VVV, EMR, BAG, EMR, BAG, EMR, VVV, GRS,
	BAG, VVV, EMR, EMR, EMR, EMR, EMR, VVV, EMR, EMR, EMR, EMR, EMR, VVV, BAG,
	EMR, CTR, CBL, EMR, EMR, EMR, EMR, VVV, EMR, EMR, EMR, EMR, CBR, CTL, EMR,
	EMR, EMR, VVV, GRS, EMR, EMR, EMR, VVV, EMR, EMR, EMR, GRS, VVV, EMR, EMR,
	EMR, EMR, CTR, HHH, CBL, EMR, EMR, VVV, EMR, EMR, CBR, HHH, CTL, EMR, EMR,
	EMR, EMR, EMR, EMR, VVV, GRS, EMR, VVV, EMR, GRS, VVV, EMR, EMR, EMR, EMR,
	EMR, EMR, EMR, EMR, CTR, CBL, GRS, VVV, GRS, CBR, CTL, EMR, EMR, EMR, EMR,
	EMR, EMR, EMR, EMR, EMR, VVV, GRS, VVV, GRS, VVV, EMR, EMR, EMR, EMR, EMR,
	EMR, EMR, EMR, EMR, EMR, CTR, HHH, T_U, HHH, CTL, EMR, EMR, EMR, EMR, EMR,
};

BANKREF(level8Map)
// emerald count 63
const unsigned char level8Map[] = {
	CBR, HHH, HHH, HHH, HHH, HHH, HHH, HHH, HHH, HHH, HHH, HHH, HHH, HHH, CBL,
	VVV, GRS, EMR, EMR, BAG, EMR, EMR, EMR, EMR, EMR, BAG, EMR, EMR, GRS, VVV,
	T_R, HHH, CBL, EMR, EMR, EMR, EMR, BAG, EMR, EMR, EMR, EMR, CBR, HHH, T_L,
	VVV, BAG, VVV, GRS, EMR, EMR, EMR, EMR, EMR, EMR, EMR, GRS, VVV, BAG, VVV,
	VVV, EMR, CTR, HHH, CBL, EMR, EMR, EMR, EMR, EMR, CBR, HHH, CTL, EMR, VVV,
	VVV, EMR, EMR, BAG, VVV, GRS, EMR, EMR, EMR, GRS, VVV, BAG, EMR, EMR, VVV,
	VVV, EMR, EMR, EMR, CTR, HHH, CBL, EMR, CBR, HHH, CTL, EMR, EMR, EMR, VVV,
	VVV, EMR, EMR, EMR, EMR, GRS, VVV, GRS, VVV, GRS, EMR, EMR, EMR, EMR, VVV,
	VVV, EMR, EMR, EMR, EMR, EMR, VVV, GRS, VVV, EMR, EMR, EMR, EMR, EMR, VVV,
	CTR, HHH, HHH, HHH, HHH, HHH, T_U, HHH, T_U, HHH, HHH, HHH, HHH, HHH, CTL,
};

BANKREF(levelDebugMap)
// emerald count 63
const unsigned char levelDebugMap[] = {
	CBR, HHH, HHH, HHH, HHH, HHH, HHH, HHH, HHH, HHH, HHH, HHH, HHH, HHH, CBL,
	CTR, HHH, HHH, HHH, HHH, HHH, HHH, HHH, HHH, HHH, HHH, HHH, HHH, HHH, CTL,
	GRS, GRS, GRS, GRS, GRS, GRS, GRS, GRS, GRS, GRS, GRS, GRS, GRS, GRS, GRS,
	GRS, GRS, BAG, BAG, BAG, BAG, BAG, BAG, GRS, GRS, GRS, GRS, GRS, GRS, VVV,
	GRS, GRS, GRS, GRS, GRS, GRS, GRS, GRS, GRS, VVV, GRS, VVV, GRS, GRS, VVV,
	GRS, GRS, BAG, GRS, BAG, GRS, GRS, BAG, GRS, GRS, GRS, BAG, GRS, GRS, VVV,
	GRS, GRS, GRS, GRS, GRS, GRS, GRS, GRS, GRS, GRS, GRS, GRS, GRS, GRS, VVV,
	GRS, GRS, BAG, BAG, BAG, BAG, BAG, BAG, GRS, GRS, GRS, GRS, GRS, GRS, VVV,
	GRS, GRS, GRS, GRS, GRS, GRS, GRS, GRS, GRS, GRS, GRS, GRS, GRS, GRS, VVV,
	GRS, GRS, GRS, GRS, GRS, GRS, HHH, HHH, HHH, HHH, HHH, HHH, HHH, HHH, CTL,
};
