#Emulicious settings file
#Sun Apr 12 23:25:02 CEST 2026
OutlineWidth=269
GameBoyErrorBreakpointSuspend19=false
GameBoyErrorBreakpointSuspend18=false
GameBoyErrorBreakpointSuspend17=false
GameBoyErrorBreakpointSuspend16=false
WindowEmuliciousWidth=800
GameBoyErrorBreakpointSuspend10=true
GameBoyErrorBreakpointCondition48=
WindowTileViewerHeight=628
DebuggerMemorySelectedTab=CPU
GameBoyErrorBreakpointCondition9=
GameBoyErrorBreakpointCondition8=
GameBoyErrorBreakpointCondition7=
GameBoyErrorBreakpointCondition6=
BankSwapAtPCBreakpointSuspend=true
GameBoyErrorBreakpointCondition5=
WindowTilemapViewerY=428
GameBoyErrorBreakpointCondition4=
DataExecutionBreakpointCondition=
WindowTilemapViewerX=554
GameBoyErrorBreakpointCondition3=
GameBoyErrorBreakpointCondition2=
GameBoyErrorBreakpointCondition1=
DataExecutionBreakpointEnabled=true
GameBoyErrorBreakpointCondition0=
WindowDebuggerWidth=1524
WindowTileViewerY=375
WindowTileViewerWidth=720
WindowTileViewerX=443
UninitializedMemoryBreakpointSuspend=true
GameBoyErrorBreakpointEnabled48=false
DebuggerConsoleLogBreakpoints=true
WindowTileViewerOpen=false
GameBoyErrorBreakpointMessage48=
DebuggerHideToolbar=false
DebuggerHideCpuUsageGraph=false
WindowTilemapViewerOpen=false
BankSwapAtPCBreakpointCondition=
Update=1
GameBoyErrorBreakpointMessage9=
GameBoyErrorBreakpointMessage8=
GameBoyErrorBreakpointMessage7=
DebuggerSouthPanelSelectedTab=0
GameBoyErrorBreakpointMessage6=
GameBoyErrorBreakpointMessage5=
GameBoyErrorBreakpointMessage4=
GameBoyErrorBreakpointMessage3=
GameBoyErrorBreakpointMessage2=
GameBoyErrorBreakpointMessage1=
GameBoyErrorBreakpointMessage0=
InterruptBreakpointEnabled=true
StackRomWriteBreakpointEnabled=true
StackWidth=1255
GameBoyErrorBreakpointCondition20=
DataExecutionBreakpointSuspend=true
UninitializedMemoryBreakpointCondition=
GameBoyErrorBreakpointSuspend48=false
SouthPanelHeight=652
WindowDebuggerOpen=false
WindowTilemapViewerWidth=502
Recent1=/Users/andreabogazzi/develop/zgb-digger/ZGB-template-master/bin/gb/Digger_Debug.gb
Recent0=/Users/andreabogazzi/develop/zgb-digger/ZGB-template-master/bin/gb/Digger.gb
GameBoyErrorBreakpointCondition19=
GameBoyErrorBreakpointCondition18=
GameBoyErrorBreakpointCondition17=
GameBoyErrorBreakpointCondition16=
GameBoyErrorBreakpointCondition10=
GameBoyErrorBreakpointEnabled20=false
DebuggerWestPanelSelectedTab=0
AudioSync=false
WindowTilemapViewerHeight=592
GameBoyErrorBreakpointMessage20=
InterruptBreakpointCondition=
FontSize=13
StackSplitLocation=-1
WindowDebuggerHeight=984
GameBoyErrorBreakpointEnabled19=false
BankSwapAtPCBreakpointEnabled=true
GameBoyErrorBreakpointEnabled18=false
GameBoyErrorBreakpointEnabled17=false
CodeFontSize=13
DebuggerMemoryTabVisibleRect=0,0,0,0
InterruptBreakpointSuspend=false
GameBoyErrorBreakpointEnabled16=false
StackRomWriteBreakpointSuspend=true
GameBoyErrorBreakpointMessage19=
GameBoyErrorBreakpointMessage18=
GameBoyErrorBreakpointMessage17=
GameBoyErrorBreakpointEnabled10=true
GameBoyErrorBreakpointMessage16=
StackRomWriteBreakpointCondition=
WindowEmuliciousHeight=748
GameBoyErrorBreakpointMessage10=
GameBoyErrorBreakpointSuspend9=false
Scale=5.0
GameBoyErrorBreakpointSuspend8=false
GameBoyErrorBreakpointSuspend7=false
GameBoyErrorBreakpointSuspend6=false
DebuggerEventFiltersGameBoy=
GameBoyErrorBreakpointSuspend5=false
GameBoyErrorBreakpointSuspend4=false
GameBoyErrorBreakpointSuspend3=false
DAPExceptionBreakpointFilters=Exception-5\:Break on inconsistent state after interrupt\:false;Exception-4\:Break on read of uninitialized memory\:false;Exception-3\:Break on execution of data\:false;Exception-2\:Break on bank swap at PC\:false;Exception-1\:Break on push to ROM\:false;Exception0\:Break on ld b, b instruction\:false;Exception1\:Break on execution of VRAM\:false;Exception2\:Break on execution of OAM\:false;Exception3\:Break on execution in port address range\:false;Exception9\:Break on write to non-standard MBC address\:false;Exception10\:Break on incorrect cartridge header\:true;Exception4\:Break on access of unusable address range\:false;Exception5\:Break on access of mirror RAM\:false;Exception6\:Break on access of SRAM while inaccessible\:false;Exception16\:Break on access of VRAM while inaccessible\:false;Exception17\:Break on access of Palette while inaccessible\:false;Exception18\:Break on access of OAM while inaccessible\:false;Exception19\:Break on turn off of LCD outside Vblank\:false;Exception8\:Break on bus conflict between CPU and OAM DMA\:false;Exception20\:Break on trigger of OAM bug\:false;Exception7\:Break on trigger of HALT bug\:false;Exception48\:Break on corruption in Wave RAM\:false
GameBoyErrorBreakpointSuspend2=false
GameBoyErrorBreakpointSuspend1=false
GameBoyErrorBreakpointSuspend0=false
GameBoyErrorBreakpointSuspend20=false
WindowDebuggerY=334
WindowDebuggerX=86
RomDir=/Users/andreabogazzi/develop/zgb-digger/ZGB-template-master/bin/gb
GameBoyErrorBreakpointEnabled9=false
DebuggerMemorySelectedAddress=0
UninitializedMemoryBreakpointEnabled=true
GameBoyErrorBreakpointEnabled8=false
GameBoyErrorBreakpointEnabled7=false
GameBoyErrorBreakpointEnabled6=false
GameBoyErrorBreakpointEnabled5=false
GameBoyErrorBreakpointEnabled4=false
GameBoyErrorBreakpointEnabled3=false
WindowEmuliciousY=374
GameBoyErrorBreakpointEnabled2=false
WindowEmuliciousX=1165
GameBoyErrorBreakpointEnabled1=false
GameBoyErrorBreakpointEnabled0=false
